### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by ealm1** [fChristenson/server-side-components#1]
How would you go about debugging this? Running into trouble setting up a launch.json debugging file in VSCode. I'm not sure if this is because of Webpack (have never used it) or something else. Any pointers would be appreciated.

**Comment by fChristenson** [comment]
If you are talking about the server code you should be able to use VSC's debugging as normal, webpack has nothing to do with this.

As for the client side code that debugging is done in the browser and not in VSC.

**Comment by ealm1** [comment]
Great, thank you!
